export interface GitHubPullRequestContext {
  number: number;
  title: string;
  headBranch: string;
  baseBranch: string;
  headSHA: string;
  url: string;
  body: string;
}

interface GitHubPullRequestPayload {
  number?: number;
  title?: string;
  headRefName?: string;
  baseRefName?: string;
  headRefOid?: string;
  url?: string;
  body?: string;
}

export type GitHubCommand = (args: string[]) => Promise<string>;

export async function findGitHubPullRequestForCommit(commitSHA: string, execute: GitHubCommand): Promise<GitHubPullRequestContext | undefined> {
  if (!commitSHA.trim()) return undefined;
  const output = await execute(['pr', 'list', '--state', 'all', '--limit', '50', '--json', 'number,title,headRefName,baseRefName,headRefOid,url,body']);
  let parsed: unknown;
  try { parsed = JSON.parse(output); } catch { throw new Error('GitHub returned invalid pull request JSON'); }
  if (!Array.isArray(parsed)) throw new Error('GitHub pull request response must be an array');
  const match = parsed.find((candidate): candidate is GitHubPullRequestPayload => Boolean(candidate && typeof candidate === 'object' && (candidate as GitHubPullRequestPayload).headRefOid === commitSHA));
  if (!match || typeof match.number !== 'number' || typeof match.title !== 'string' || typeof match.headRefName !== 'string' || typeof match.baseRefName !== 'string' || typeof match.headRefOid !== 'string' || typeof match.url !== 'string') return undefined;
  return { number: match.number, title: match.title, headBranch: match.headRefName, baseBranch: match.baseRefName, headSHA: match.headRefOid, url: match.url, body: typeof match.body === 'string' ? match.body : '' };
}

export function buildCIRepairComment(input: { runID: number; commit: string; summary: string; repairSessionID: string; result: string }): string {
  return [
    '## DeepSeek Code CI repair',
    '',
    `- GitHub Actions Run #${input.runID}`,
    `- Commit: \`${input.commit}\``,
    `- Repair Session: \`${input.repairSessionID}\``,
    '',
    '### Failure classification',
    input.summary.slice(0, 4_000),
    '',
    '### Result',
    input.result.slice(0, 10_000),
    '',
    '_This comment was generated by the local DeepSeek Code runtime; it does not grant permission to push or merge._'
  ].join('\n').slice(0, 19_500);
}

export async function updateGitHubPullRequest(number: number, body: string, execute: GitHubCommand): Promise<{ number: number; updated: true }> {
  if (!Number.isInteger(number) || number < 1) throw new Error('A valid pull request number is required');
  if (!body.trim()) throw new Error('Pull request comment body is required');
  await execute(['pr', 'comment', String(number), '--body', body.slice(0, 19_500)]);
  return { number, updated: true };
}
